// ---------------------------------------------------- \\
// Sdk Generated By ( Unreal Finder Tool.Net By CorrM ) \\
// ---------------------------------------------------- \\

	public static class Sdk
{
		public static ExternalMemorySharp MainEms { get; private set; }
		public static bool SetupSdk(ExternalMemorySharp ems) { }

	}
}