// Name: Sq, Version: b21

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace UFT
{
//---------------------------------------------------------------------------
// Classes
//---------------------------------------------------------------------------

// WidgetBlueprintGeneratedClass MainMenuScreen.MainMenuScreen_C
// 0x0474 (0x0654 - 0x01E0)
public class UMainMenuScreen_C : UUserWidget
{
	#region Offsets
	private ExternalOffset<FPointerToUberGraphFrame>          _offUberGraphFrame                                             = new ExternalOffset<FPointerToUberGraphFrame>(0x0230, false); // 0x0230(0x0008) (ZeroConstructor, Transient, DuplicateTransient)
	private ExternalOffset<UMainMenu_Button_C>                _offAudioApply                                                 = new ExternalOffset<UMainMenu_Button_C>(0x0238, true);        // 0x0238(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offAudioDefaults                                              = new ExternalOffset<UMainMenu_Button_C>(0x0240, true);        // 0x0240(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UAudioWindow_C>                    _offAudioSettings                                              = new ExternalOffset<UAudioWindow_C>(0x0248, true);            // 0x0248(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offBlockInput                                                 = new ExternalOffset<UImage>(0x0250, true);                    // 0x0250(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UButton>                           _offButton_BackToMain                                          = new ExternalOffset<UButton>(0x0258, true);                   // 0x0258(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UButton>                           _offButton_HideHUD                                             = new ExternalOffset<UButton>(0x0260, true);                   // 0x0260(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offButton_ModsRefresh                                         = new ExternalOffset<UMainMenu_Button_C>(0x0268, true);        // 0x0268(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offButtonCREDITS                                              = new ExternalOffset<UMainMenu_Button_C>(0x0270, true);        // 0x0270(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offButtonCUSTOMSERVERS                                        = new ExternalOffset<UMainMenu_Button_C>(0x0278, true);        // 0x0278(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UButton>                           _offButtonEXIT                                                 = new ExternalOffset<UButton>(0x0280, true);                   // 0x0280(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offButtonFRIENDS                                              = new ExternalOffset<UMainMenu_Button_C>(0x0288, true);        // 0x0288(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offButtonRefreshAllServers                                    = new ExternalOffset<UMainMenu_Button_C>(0x0290, true);        // 0x0290(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offButtonRefreshFriends                                       = new ExternalOffset<UMainMenu_Button_C>(0x0298, true);        // 0x0298(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offButtonResetFilters                                         = new ExternalOffset<UMainMenu_Button_C>(0x02A0, true);        // 0x02A0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offButtonRestoreDefaultControls                               = new ExternalOffset<UMainMenu_Button_C>(0x02A8, true);        // 0x02A8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offButtonSERVERBROWSER                                        = new ExternalOffset<UMainMenu_Button_C>(0x02B0, true);        // 0x02B0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offButtonSETTINGS                                             = new ExternalOffset<UMainMenu_Button_C>(0x02B8, true);        // 0x02B8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offButtonSettingsAUDIO                                        = new ExternalOffset<UMainMenu_Button_C>(0x02C0, true);        // 0x02C0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offButtonSettingsCONTROLS                                     = new ExternalOffset<UMainMenu_Button_C>(0x02C8, true);        // 0x02C8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offButtonSettingsGAME                                         = new ExternalOffset<UMainMenu_Button_C>(0x02D0, true);        // 0x02D0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offButtonSettingsGRAPHICS                                     = new ExternalOffset<UMainMenu_Button_C>(0x02D8, true);        // 0x02D8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offButtonSettingsSTEAM                                        = new ExternalOffset<UMainMenu_Button_C>(0x02E0, true);        // 0x02E0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offButtonSettingsUI                                           = new ExternalOffset<UMainMenu_Button_C>(0x02E8, true);        // 0x02E8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offButtonTRAIN                                                = new ExternalOffset<UMainMenu_Button_C>(0x02F0, true);        // 0x02F0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UCanvasPanel>                      _offCanvasPanel_129                                            = new ExternalOffset<UCanvasPanel>(0x02F8, true);              // 0x02F8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UHorizontalBox>                    _offContext_Audio                                              = new ExternalOffset<UHorizontalBox>(0x0300, true);            // 0x0300(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UHorizontalBox>                    _offContext_Controls                                           = new ExternalOffset<UHorizontalBox>(0x0308, true);            // 0x0308(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UHorizontalBox>                    _offContext_FriendsList                                        = new ExternalOffset<UHorizontalBox>(0x0310, true);            // 0x0310(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UHorizontalBox>                    _offContext_GameSettings                                       = new ExternalOffset<UHorizontalBox>(0x0318, true);            // 0x0318(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UHorizontalBox>                    _offContext_Graphics                                           = new ExternalOffset<UHorizontalBox>(0x0320, true);            // 0x0320(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UHorizontalBox>                    _offContext_Mods                                               = new ExternalOffset<UHorizontalBox>(0x0328, true);            // 0x0328(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UHorizontalBox>                    _offContext_Server                                             = new ExternalOffset<UHorizontalBox>(0x0330, true);            // 0x0330(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UHorizontalBox>                    _offContext_SteamItems                                         = new ExternalOffset<UHorizontalBox>(0x0338, true);            // 0x0338(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UControlsWindow_C>                 _offControlsSettings                                           = new ExternalOffset<UControlsWindow_C>(0x0340, true);         // 0x0340(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UCreditsWindow_C>                  _offCreditsWindow                                              = new ExternalOffset<UCreditsWindow_C>(0x0348, true);          // 0x0348(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UServerBrowserWindow_C>            _offCustomBrowser                                              = new ExternalOffset<UServerBrowserWindow_C>(0x0350, true);    // 0x0350(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UServerBrowserWindow_C>            _offDedicatedBrowser                                           = new ExternalOffset<UServerBrowserWindow_C>(0x0358, true);    // 0x0358(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<USizeBox>                          _offDisconnectWindow                                           = new ExternalOffset<USizeBox>(0x0360, true);                  // 0x0360(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<USizeBox>                          _offExitWindow                                                 = new ExternalOffset<USizeBox>(0x0368, true);                  // 0x0368(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offEye                                                        = new ExternalOffset<UImage>(0x0370, true);                    // 0x0370(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UFriendsBrowserWindow_C>           _offFriendsBrowserWindow                                       = new ExternalOffset<UFriendsBrowserWindow_C>(0x0378, true);   // 0x0378(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offGameApply                                                  = new ExternalOffset<UMainMenu_Button_C>(0x0380, true);        // 0x0380(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offGameDebug                                                  = new ExternalOffset<UMainMenu_Button_C>(0x0388, true);        // 0x0388(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offGameDefaults                                               = new ExternalOffset<UMainMenu_Button_C>(0x0390, true);        // 0x0390(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offGameReset                                                  = new ExternalOffset<UMainMenu_Button_C>(0x0398, true);        // 0x0398(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UGameSettingsWindow_C>             _offGameSettings                                               = new ExternalOffset<UGameSettingsWindow_C>(0x03A0, true);     // 0x03A0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offGraphicsApply                                              = new ExternalOffset<UMainMenu_Button_C>(0x03A8, true);        // 0x03A8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offGraphicsBenchmark                                          = new ExternalOffset<UMainMenu_Button_C>(0x03B0, true);        // 0x03B0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offGraphicsDefaults                                           = new ExternalOffset<UMainMenu_Button_C>(0x03B8, true);        // 0x03B8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UGraphicsWindow_C>                 _offGraphicsSettings                                           = new ExternalOffset<UGraphicsWindow_C>(0x03C0, true);         // 0x03C0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offHideHUDBar                                                 = new ExternalOffset<UImage>(0x03C8, true);                    // 0x03C8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offImage_1                                                    = new ExternalOffset<UImage>(0x03D0, true);                    // 0x03D0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offImage_2                                                    = new ExternalOffset<UImage>(0x03D8, true);                    // 0x03D8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offImage_3                                                    = new ExternalOffset<UImage>(0x03E0, true);                    // 0x03E0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offImage_4                                                    = new ExternalOffset<UImage>(0x03E8, true);                    // 0x03E8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offImage_5                                                    = new ExternalOffset<UImage>(0x03F0, true);                    // 0x03F0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offImage_SteamOnline                                          = new ExternalOffset<UImage>(0x03F8, true);                    // 0x03F8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UBorder>                           _offInGameBlackoutBG                                           = new ExternalOffset<UBorder>(0x0400, true);                   // 0x0400(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UInputCapture_C>                   _offInputCaptureWidget                                         = new ExternalOffset<UInputCapture_C>(0x0408, true);           // 0x0408(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UInvalidPasswordWidget_C>          _offInvalidPassword                                            = new ExternalOffset<UInvalidPasswordWidget_C>(0x0410, true);  // 0x0410(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UThrobber>                         _offJoinThrobber                                               = new ExternalOffset<UThrobber>(0x0418, true);                 // 0x0418(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UCanvasPanel>                      _offLandingCanvas                                              = new ExternalOffset<UCanvasPanel>(0x0420, true);              // 0x0420(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UChallengeWindow_C>                _offLeaveQueueConfirm                                          = new ExternalOffset<UChallengeWindow_C>(0x0428, true);        // 0x0428(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offLineBottom                                                 = new ExternalOffset<UImage>(0x0430, true);                    // 0x0430(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offLineTop                                                    = new ExternalOffset<UImage>(0x0438, true);                    // 0x0438(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UModBrowser_C>                     _offModBrowser                                                 = new ExternalOffset<UModBrowser_C>(0x0440, true);             // 0x0440(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UModBrowser_C>                     _offModBrowser_90                                              = new ExternalOffset<UModBrowser_C>(0x0448, true);             // 0x0448(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMusicPlayer_C>                    _offMusicPlayer                                                = new ExternalOffset<UMusicPlayer_C>(0x0450, true);            // 0x0450(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UVerticalBox>                      _offNavigationHorizontalBox                                    = new ExternalOffset<UVerticalBox>(0x0458, true);              // 0x0458(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UTextBlock>                        _offPendingServerText                                          = new ExternalOffset<UTextBlock>(0x0460, true);                // 0x0460(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UChallengeWindow_C>                _offPopupDisconnect                                            = new ExternalOffset<UChallengeWindow_C>(0x0468, true);        // 0x0468(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UChallengeWindow_C>                _offPopupExit                                                  = new ExternalOffset<UChallengeWindow_C>(0x0470, true);        // 0x0470(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UChallengeWindow_C>                _offPopupLocalGame                                             = new ExternalOffset<UChallengeWindow_C>(0x0478, true);        // 0x0478(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UChallengeWindow_C>                _offResetDataConfirm                                           = new ExternalOffset<UChallengeWindow_C>(0x0480, true);        // 0x0480(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UWidgetSwitcher>                   _offSecondaryNavSectionSwitcher                                = new ExternalOffset<UWidgetSwitcher>(0x0488, true);           // 0x0488(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UChallengeWindow_C>                _offServerConfirm                                              = new ExternalOffset<UChallengeWindow_C>(0x0490, true);        // 0x0490(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UBorder>                           _offServerFriendsWindow                                        = new ExternalOffset<UBorder>(0x0498, true);                   // 0x0498(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UOverlay>                          _offServerOverlay                                              = new ExternalOffset<UOverlay>(0x04A0, true);                  // 0x04A0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UWidgetSwitcher>                   _offServerSwitch                                               = new ExternalOffset<UWidgetSwitcher>(0x04A8, true);           // 0x04A8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UHorizontalBox>                    _offSettingsNav                                                = new ExternalOffset<UHorizontalBox>(0x04B0, true);            // 0x04B0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UBorder>                           _offSettingsPanel                                              = new ExternalOffset<UBorder>(0x04B8, true);                   // 0x04B8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UWidgetSwitcher>                   _offSettingsSwitcher                                           = new ExternalOffset<UWidgetSwitcher>(0x04C0, true);           // 0x04C0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<USpacer>                           _offSpacer_BottomContext                                       = new ExternalOffset<USpacer>(0x04C8, true);                   // 0x04C8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<USpacer>                           _offSpacer_SecNav                                              = new ExternalOffset<USpacer>(0x04D0, true);                   // 0x04D0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<USQNetInfoWidgetSlot_C>            _offSQNetInfoWidgetSlot_Development                            = new ExternalOffset<USQNetInfoWidgetSlot_C>(0x04D8, true);    // 0x04D8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<USizeBox>                          _offStartLocalWindow                                           = new ExternalOffset<USizeBox>(0x04E0, true);                  // 0x04E0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offSteamInventoryApply                                        = new ExternalOffset<UMainMenu_Button_C>(0x04E8, true);        // 0x04E8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offSteamInventoryDefaults                                     = new ExternalOffset<UMainMenu_Button_C>(0x04F0, true);        // 0x04F0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<USteamInventorySettings_C>         _offSteamInventorySettings                                     = new ExternalOffset<USteamInventorySettings_C>(0x04F8, true); // 0x04F8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UWidgetSwitcher>                   _offSwitcher_BottomContext                                     = new ExternalOffset<UWidgetSwitcher>(0x0500, true);           // 0x0500(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UWidgetSwitcher>                   _offSwitcherMain                                               = new ExternalOffset<UWidgetSwitcher>(0x0508, true);           // 0x0508(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UWidgetSwitcher>                   _offSwitcherTitle                                              = new ExternalOffset<UWidgetSwitcher>(0x0510, true);           // 0x0510(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UTextBlock>                        _offTB_Title                                                   = new ExternalOffset<UTextBlock>(0x0518, true);                // 0x0518(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<USizeBox>                          _offTrainingWindow                                             = new ExternalOffset<USizeBox>(0x0520, true);                  // 0x0520(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UTravelQueueWidget_C>              _offTravelQueueWidget                                          = new ExternalOffset<UTravelQueueWidget_C>(0x0528, true);      // 0x0528(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<ULevelSelector_C>                  _offTutorial_LevelSelector                                     = new ExternalOffset<ULevelSelector_C>(0x0530, true);          // 0x0530(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UUISettingsWindow_C>               _offUISettings                                                 = new ExternalOffset<UUISettingsWindow_C>(0x0538, true);       // 0x0538(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UVersionWidget_C>                  _offVersionWidget                                              = new ExternalOffset<UVersionWidget_C>(0x0540, true);          // 0x0540(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_Filters_C>                      _offW_Filters                                                  = new ExternalOffset<UW_Filters_C>(0x0548, true);              // 0x0548(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_Training_LevelList_C>           _offW_LevelList                                                = new ExternalOffset<UW_Training_LevelList_C>(0x0550, true);   // 0x0550(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UWidgetSwitcher>                   _offWidgetSwitcher_Pending                                     = new ExternalOffset<UWidgetSwitcher>(0x0558, true);           // 0x0558(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UWidgetSwitcher>                   _offWidgetSwitcher_SteamStatus                                 = new ExternalOffset<UWidgetSwitcher>(0x0560, true);           // 0x0560(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<float>                             _offFadeProgress                                               = new ExternalOffset<float>(0x0568);                           // 0x0568(0x0004) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	private ExternalOffset<byte/*(bool)*/>                    _offbFading                                                    = new ExternalOffset<byte/*(bool)*/>(0x056C);                  // 0x056C(0x0001) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	private ExternalOffset<byte/*(bool)*/>                    _offbWantsToBeVisible                                          = new ExternalOffset<byte/*(bool)*/>(0x056D);                  // 0x056D(0x0001) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	private ExternalOffset<byte/*(bool)*/>                    _offbCheckUpdate                                               = new ExternalOffset<byte/*(bool)*/>(0x056E);                  // 0x056E(0x0001) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	private ExternalOffset<byte/*(bool)*/>                    _offbShowServerConfirmation                                    = new ExternalOffset<byte/*(bool)*/>(0x056F);                  // 0x056F(0x0001) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	private ExternalOffset<UServerBrowserWindow_C>            _offCurrent_Browser                                            = new ExternalOffset<UServerBrowserWindow_C>(0x0570, true);    // 0x0570(0x0008) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_ExitButtons_C>           _offExitButtons                                                = new ExternalOffset<UMainMenu_ExitButtons_C>(0x0578, true);   // 0x0578(0x0008) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	private ExternalOffset<byte/*(bool)*/>                    _offIs_Browsing_Dedicated                                      = new ExternalOffset<byte/*(bool)*/>(0x0580);                  // 0x0580(0x0001) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	private ExternalOffset<AMenuCamPawn_C>                    _offMy_Menu_Cam_Pawn                                           = new ExternalOffset<AMenuCamPawn_C>(0x0588, true);            // 0x0588(0x0008) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	private ExternalOffset<byte/*(bool)*/>                    _offShow_Leave_Queue_Challenge                                 = new ExternalOffset<byte/*(bool)*/>(0x0590);                  // 0x0590(0x0001) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	private ExternalOffset<FBlueprintSessionResult>           _offCached_Session                                             = new ExternalOffset<FBlueprintSessionResult>(0x0598, false);  // 0x0598(0x00B8) (Edit, BlueprintVisible, DisableEditOnInstance)
	private ExternalOffset<byte/*(bool)*/>                    _offSession_Cached                                             = new ExternalOffset<byte/*(bool)*/>(0x0650);                  // 0x0650(0x0001) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	private ExternalOffset<byte/*(bool)*/>                    _offBlock_Input_Visible                                        = new ExternalOffset<byte/*(bool)*/>(0x0651);                  // 0x0651(0x0001) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	private ExternalOffset<byte/*(bool)*/>                    _offIs_In_Queue                                                = new ExternalOffset<byte/*(bool)*/>(0x0652);                  // 0x0652(0x0001) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	private ExternalOffset<byte/*(bool)*/>                    _offbHideHud                                                   = new ExternalOffset<byte/*(bool)*/>(0x0653);                  // 0x0653(0x0001) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	#endregion

	#region Props
	public FPointerToUberGraphFrame                           UberGraphFrame                                                 => _offUberGraphFrame.GetValue();
	public UMainMenu_Button_C                                 AudioApply                                                     => _offAudioApply.GetValue();
	public UMainMenu_Button_C                                 AudioDefaults                                                  => _offAudioDefaults.GetValue();
	public UAudioWindow_C                                     AudioSettings                                                  => _offAudioSettings.GetValue();
	public UImage                                             BlockInput                                                     => _offBlockInput.GetValue();
	public UButton                                            Button_BackToMain                                              => _offButton_BackToMain.GetValue();
	public UButton                                            Button_HideHUD                                                 => _offButton_HideHUD.GetValue();
	public UMainMenu_Button_C                                 Button_ModsRefresh                                             => _offButton_ModsRefresh.GetValue();
	public UMainMenu_Button_C                                 ButtonCREDITS                                                  => _offButtonCREDITS.GetValue();
	public UMainMenu_Button_C                                 ButtonCUSTOMSERVERS                                            => _offButtonCUSTOMSERVERS.GetValue();
	public UButton                                            ButtonEXIT                                                     => _offButtonEXIT.GetValue();
	public UMainMenu_Button_C                                 ButtonFRIENDS                                                  => _offButtonFRIENDS.GetValue();
	public UMainMenu_Button_C                                 ButtonRefreshAllServers                                        => _offButtonRefreshAllServers.GetValue();
	public UMainMenu_Button_C                                 ButtonRefreshFriends                                           => _offButtonRefreshFriends.GetValue();
	public UMainMenu_Button_C                                 ButtonResetFilters                                             => _offButtonResetFilters.GetValue();
	public UMainMenu_Button_C                                 ButtonRestoreDefaultControls                                   => _offButtonRestoreDefaultControls.GetValue();
	public UMainMenu_Button_C                                 ButtonSERVERBROWSER                                            => _offButtonSERVERBROWSER.GetValue();
	public UMainMenu_Button_C                                 ButtonSETTINGS                                                 => _offButtonSETTINGS.GetValue();
	public UMainMenu_Button_C                                 ButtonSettingsAUDIO                                            => _offButtonSettingsAUDIO.GetValue();
	public UMainMenu_Button_C                                 ButtonSettingsCONTROLS                                         => _offButtonSettingsCONTROLS.GetValue();
	public UMainMenu_Button_C                                 ButtonSettingsGAME                                             => _offButtonSettingsGAME.GetValue();
	public UMainMenu_Button_C                                 ButtonSettingsGRAPHICS                                         => _offButtonSettingsGRAPHICS.GetValue();
	public UMainMenu_Button_C                                 ButtonSettingsSTEAM                                            => _offButtonSettingsSTEAM.GetValue();
	public UMainMenu_Button_C                                 ButtonSettingsUI                                               => _offButtonSettingsUI.GetValue();
	public UMainMenu_Button_C                                 ButtonTRAIN                                                    => _offButtonTRAIN.GetValue();
	public UCanvasPanel                                       CanvasPanel_129                                                => _offCanvasPanel_129.GetValue();
	public UHorizontalBox                                     Context_Audio                                                  => _offContext_Audio.GetValue();
	public UHorizontalBox                                     Context_Controls                                               => _offContext_Controls.GetValue();
	public UHorizontalBox                                     Context_FriendsList                                            => _offContext_FriendsList.GetValue();
	public UHorizontalBox                                     Context_GameSettings                                           => _offContext_GameSettings.GetValue();
	public UHorizontalBox                                     Context_Graphics                                               => _offContext_Graphics.GetValue();
	public UHorizontalBox                                     Context_Mods                                                   => _offContext_Mods.GetValue();
	public UHorizontalBox                                     Context_Server                                                 => _offContext_Server.GetValue();
	public UHorizontalBox                                     Context_SteamItems                                             => _offContext_SteamItems.GetValue();
	public UControlsWindow_C                                  ControlsSettings                                               => _offControlsSettings.GetValue();
	public UCreditsWindow_C                                   CreditsWindow                                                  => _offCreditsWindow.GetValue();
	public UServerBrowserWindow_C                             CustomBrowser                                                  => _offCustomBrowser.GetValue();
	public UServerBrowserWindow_C                             DedicatedBrowser                                               => _offDedicatedBrowser.GetValue();
	public USizeBox                                           DisconnectWindow                                               => _offDisconnectWindow.GetValue();
	public USizeBox                                           ExitWindow                                                     => _offExitWindow.GetValue();
	public UImage                                             Eye                                                            => _offEye.GetValue();
	public UFriendsBrowserWindow_C                            FriendsBrowserWindow                                           => _offFriendsBrowserWindow.GetValue();
	public UMainMenu_Button_C                                 GameApply                                                      => _offGameApply.GetValue();
	public UMainMenu_Button_C                                 GameDebug                                                      => _offGameDebug.GetValue();
	public UMainMenu_Button_C                                 GameDefaults                                                   => _offGameDefaults.GetValue();
	public UMainMenu_Button_C                                 GameReset                                                      => _offGameReset.GetValue();
	public UGameSettingsWindow_C                              GameSettings                                                   => _offGameSettings.GetValue();
	public UMainMenu_Button_C                                 GraphicsApply                                                  => _offGraphicsApply.GetValue();
	public UMainMenu_Button_C                                 GraphicsBenchmark                                              => _offGraphicsBenchmark.GetValue();
	public UMainMenu_Button_C                                 GraphicsDefaults                                               => _offGraphicsDefaults.GetValue();
	public UGraphicsWindow_C                                  GraphicsSettings                                               => _offGraphicsSettings.GetValue();
	public UImage                                             HideHUDBar                                                     => _offHideHUDBar.GetValue();
	public UImage                                             Image_1                                                        => _offImage_1.GetValue();
	public UImage                                             Image_2                                                        => _offImage_2.GetValue();
	public UImage                                             Image_3                                                        => _offImage_3.GetValue();
	public UImage                                             Image_4                                                        => _offImage_4.GetValue();
	public UImage                                             Image_5                                                        => _offImage_5.GetValue();
	public UImage                                             Image_SteamOnline                                              => _offImage_SteamOnline.GetValue();
	public UBorder                                            InGameBlackoutBG                                               => _offInGameBlackoutBG.GetValue();
	public UInputCapture_C                                    InputCaptureWidget                                             => _offInputCaptureWidget.GetValue();
	public UInvalidPasswordWidget_C                           InvalidPassword                                                => _offInvalidPassword.GetValue();
	public UThrobber                                          JoinThrobber                                                   => _offJoinThrobber.GetValue();
	public UCanvasPanel                                       LandingCanvas                                                  => _offLandingCanvas.GetValue();
	public UChallengeWindow_C                                 LeaveQueueConfirm                                              => _offLeaveQueueConfirm.GetValue();
	public UImage                                             LineBottom                                                     => _offLineBottom.GetValue();
	public UImage                                             LineTop                                                        => _offLineTop.GetValue();
	public UModBrowser_C                                      ModBrowser                                                     => _offModBrowser.GetValue();
	public UModBrowser_C                                      ModBrowser_90                                                  => _offModBrowser_90.GetValue();
	public UMusicPlayer_C                                     MusicPlayer                                                    => _offMusicPlayer.GetValue();
	public UVerticalBox                                       NavigationHorizontalBox                                        => _offNavigationHorizontalBox.GetValue();
	public UTextBlock                                         PendingServerText                                              => _offPendingServerText.GetValue();
	public UChallengeWindow_C                                 PopupDisconnect                                                => _offPopupDisconnect.GetValue();
	public UChallengeWindow_C                                 PopupExit                                                      => _offPopupExit.GetValue();
	public UChallengeWindow_C                                 PopupLocalGame                                                 => _offPopupLocalGame.GetValue();
	public UChallengeWindow_C                                 ResetDataConfirm                                               => _offResetDataConfirm.GetValue();
	public UWidgetSwitcher                                    SecondaryNavSectionSwitcher                                    => _offSecondaryNavSectionSwitcher.GetValue();
	public UChallengeWindow_C                                 ServerConfirm                                                  => _offServerConfirm.GetValue();
	public UBorder                                            ServerFriendsWindow                                            => _offServerFriendsWindow.GetValue();
	public UOverlay                                           ServerOverlay                                                  => _offServerOverlay.GetValue();
	public UWidgetSwitcher                                    ServerSwitch                                                   => _offServerSwitch.GetValue();
	public UHorizontalBox                                     SettingsNav                                                    => _offSettingsNav.GetValue();
	public UBorder                                            SettingsPanel                                                  => _offSettingsPanel.GetValue();
	public UWidgetSwitcher                                    SettingsSwitcher                                               => _offSettingsSwitcher.GetValue();
	public USpacer                                            Spacer_BottomContext                                           => _offSpacer_BottomContext.GetValue();
	public USpacer                                            Spacer_SecNav                                                  => _offSpacer_SecNav.GetValue();
	public USQNetInfoWidgetSlot_C                             SQNetInfoWidgetSlot_Development                                => _offSQNetInfoWidgetSlot_Development.GetValue();
	public USizeBox                                           StartLocalWindow                                               => _offStartLocalWindow.GetValue();
	public UMainMenu_Button_C                                 SteamInventoryApply                                            => _offSteamInventoryApply.GetValue();
	public UMainMenu_Button_C                                 SteamInventoryDefaults                                         => _offSteamInventoryDefaults.GetValue();
	public USteamInventorySettings_C                          SteamInventorySettings                                         => _offSteamInventorySettings.GetValue();
	public UWidgetSwitcher                                    Switcher_BottomContext                                         => _offSwitcher_BottomContext.GetValue();
	public UWidgetSwitcher                                    SwitcherMain                                                   => _offSwitcherMain.GetValue();
	public UWidgetSwitcher                                    SwitcherTitle                                                  => _offSwitcherTitle.GetValue();
	public UTextBlock                                         TB_Title                                                       => _offTB_Title.GetValue();
	public USizeBox                                           TrainingWindow                                                 => _offTrainingWindow.GetValue();
	public UTravelQueueWidget_C                               TravelQueueWidget                                              => _offTravelQueueWidget.GetValue();
	public ULevelSelector_C                                   Tutorial_LevelSelector                                         => _offTutorial_LevelSelector.GetValue();
	public UUISettingsWindow_C                                UISettings                                                     => _offUISettings.GetValue();
	public UVersionWidget_C                                   VersionWidget                                                  => _offVersionWidget.GetValue();
	public UW_Filters_C                                       W_Filters                                                      => _offW_Filters.GetValue();
	public UW_Training_LevelList_C                            W_LevelList                                                    => _offW_LevelList.GetValue();
	public UWidgetSwitcher                                    WidgetSwitcher_Pending                                         => _offWidgetSwitcher_Pending.GetValue();
	public UWidgetSwitcher                                    WidgetSwitcher_SteamStatus                                     => _offWidgetSwitcher_SteamStatus.GetValue();
	public float                                              FadeProgress                                                   => _offFadeProgress.GetValue();
	public byte/*(bool)*/                                     bFading                                                        => _offbFading.GetValue();
	public byte/*(bool)*/                                     bWantsToBeVisible                                              => _offbWantsToBeVisible.GetValue();
	public byte/*(bool)*/                                     bCheckUpdate                                                   => _offbCheckUpdate.GetValue();
	public byte/*(bool)*/                                     bShowServerConfirmation                                        => _offbShowServerConfirmation.GetValue();
	public UServerBrowserWindow_C                             Current_Browser                                                => _offCurrent_Browser.GetValue();
	public UMainMenu_ExitButtons_C                            ExitButtons                                                    => _offExitButtons.GetValue();
	public byte/*(bool)*/                                     Is_Browsing_Dedicated                                          => _offIs_Browsing_Dedicated.GetValue();
	public AMenuCamPawn_C                                     My_Menu_Cam_Pawn                                               => _offMy_Menu_Cam_Pawn.GetValue();
	public byte/*(bool)*/                                     Show_Leave_Queue_Challenge                                     => _offShow_Leave_Queue_Challenge.GetValue();
	public FBlueprintSessionResult                            Cached_Session                                                 => _offCached_Session.GetValue();
	public byte/*(bool)*/                                     Session_Cached                                                 => _offSession_Cached.GetValue();
	public byte/*(bool)*/                                     Block_Input_Visible                                            => _offBlock_Input_Visible.GetValue();
	public byte/*(bool)*/                                     Is_In_Queue                                                    => _offIs_In_Queue.GetValue();
	public byte/*(bool)*/                                     bHideHud                                                       => _offbHideHud.GetValue();
	#endregion


}


}