// Name: Sq, Version: b21

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace UFT
{
//---------------------------------------------------------------------------
// Classes
//---------------------------------------------------------------------------

// WidgetBlueprintGeneratedClass W_DeploymentMenu.W_DeploymentMenu_C
// 0x01A0 (0x0450 - 0x02B0)
public class UW_DeploymentMenu_C : UUMG_MenuBase_C
{
	#region Offsets
	private ExternalOffset<FPointerToUberGraphFrame>          _offUberGraphFrame                                             = new ExternalOffset<FPointerToUberGraphFrame>(0x02B0, false); // 0x02B0(0x0008) (ZeroConstructor, Transient, DuplicateTransient)
	private ExternalOffset<UWidgetAnimation>                  _offLoadFade                                                   = new ExternalOffset<UWidgetAnimation>(0x02B8, true);          // 0x02B8(0x0008) (BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	private ExternalOffset<UWidgetAnimation>                  _offCentreTransition                                           = new ExternalOffset<UWidgetAnimation>(0x02C0, true);          // 0x02C0(0x0008) (BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	private ExternalOffset<UWidgetAnimation>                  _offBlackTransition                                            = new ExternalOffset<UWidgetAnimation>(0x02C8, true);          // 0x02C8(0x0008) (BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	private ExternalOffset<UWidgetAnimation>                  _offDeploymentOpenCloseAnim                                    = new ExternalOffset<UWidgetAnimation>(0x02D0, true);          // 0x02D0(0x0008) (BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	private ExternalOffset<UBorder>                           _offBlackout                                                   = new ExternalOffset<UBorder>(0x02D8, true);                   // 0x02D8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offBlockInput                                                 = new ExternalOffset<UImage>(0x02E0, true);                    // 0x02E0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offBottomBarRole                                              = new ExternalOffset<UMainMenu_Button_C>(0x02E8, true);        // 0x02E8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UWidgetSwitcher>                   _offBottomSwitcher                                             = new ExternalOffset<UWidgetSwitcher>(0x02F0, true);           // 0x02F0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UChallengeWindow_C>                _offChallengeGiveUp                                            = new ExternalOffset<UChallengeWindow_C>(0x02F8, true);        // 0x02F8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UChallengeWindow_C>                _offChallengeLeaveSquad                                        = new ExternalOffset<UChallengeWindow_C>(0x0300, true);        // 0x0300(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UChallengeWindow_C>                _offChallengeLeaveTeam                                         = new ExternalOffset<UChallengeWindow_C>(0x0308, true);        // 0x0308(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offDeployArrow                                                = new ExternalOffset<UImage>(0x0310, true);                    // 0x0310(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offDeployButton                                               = new ExternalOffset<UMainMenu_Button_C>(0x0318, true);        // 0x0318(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<USizeBox>                          _offGiveupPanel                                                = new ExternalOffset<USizeBox>(0x0320, true);                  // 0x0320(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offImage_1                                                    = new ExternalOffset<UImage>(0x0328, true);                    // 0x0328(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offImage_9                                                    = new ExternalOffset<UImage>(0x0330, true);                    // 0x0330(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offImage_BGFlag                                               = new ExternalOffset<UImage>(0x0338, true);                    // 0x0338(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offImage_FlagTopRight                                         = new ExternalOffset<UImage>(0x0340, true);                    // 0x0340(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offLine                                                       = new ExternalOffset<UImage>(0x0348, true);                    // 0x0348(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offLineBottom                                                 = new ExternalOffset<UImage>(0x0350, true);                    // 0x0350(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UCanvasPanel>                      _offMainPanel                                                  = new ExternalOffset<UCanvasPanel>(0x0358, true);              // 0x0358(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offNAV_ROLES                                                  = new ExternalOffset<UMainMenu_Button_C>(0x0360, true);        // 0x0360(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offNAV_SQUADS                                                 = new ExternalOffset<UMainMenu_Button_C>(0x0368, true);        // 0x0368(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UMainMenu_Button_C>                _offNAV_TEAMSELECT                                             = new ExternalOffset<UMainMenu_Button_C>(0x0370, true);        // 0x0370(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UOverlay>                          _offOverlay_DeployButton                                       = new ExternalOffset<UOverlay>(0x0378, true);                  // 0x0378(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_RoleSelect_C>                   _offRoleScreen                                                 = new ExternalOffset<UW_RoleSelect_C>(0x0380, true);           // 0x0380(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<USizeBox>                          _offSize_Centre                                                = new ExternalOffset<USizeBox>(0x0388, true);                  // 0x0388(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_SquadSelect_C>                  _offSquadScreen                                                = new ExternalOffset<UW_SquadSelect_C>(0x0390, true);          // 0x0390(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UWidgetSwitcher>                   _offSwitchCentre                                               = new ExternalOffset<UWidgetSwitcher>(0x0398, true);           // 0x0398(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UWidgetSwitcher>                   _offSwitchLoad                                                 = new ExternalOffset<UWidgetSwitcher>(0x03A0, true);           // 0x03A0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UTextBlock>                        _offTB_ServerName                                              = new ExternalOffset<UTextBlock>(0x03A8, true);                // 0x03A8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UTextBlock>                        _offTB_TeamName                                                = new ExternalOffset<UTextBlock>(0x03B0, true);                // 0x03B0(0x0008) (ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UTextBlock>                        _offTB_Title                                                   = new ExternalOffset<UTextBlock>(0x03B8, true);                // 0x03B8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_TeamSelect_C>                   _offTeamScreen                                                 = new ExternalOffset<UW_TeamSelect_C>(0x03C0, true);           // 0x03C0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UHorizontalBox>                    _offTopNavigation                                              = new ExternalOffset<UHorizontalBox>(0x03C8, true);            // 0x03C8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_GameTime_C>                     _offW_GameTime                                                 = new ExternalOffset<UW_GameTime_C>(0x03D0, true);             // 0x03D0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_GameTime_C>                     _offW_GameTime_3                                               = new ExternalOffset<UW_GameTime_C>(0x03D8, true);             // 0x03D8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_GiveUp_C>                       _offW_GiveUp                                                   = new ExternalOffset<UW_GiveUp_C>(0x03E0, true);               // 0x03E0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_PlayerRankAndRole_C>            _offW_PlayerRankAndRole                                        = new ExternalOffset<UW_PlayerRankAndRole_C>(0x03E8, true);    // 0x03E8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_TeamTickets_C>                  _offW_TeamTickets                                              = new ExternalOffset<UW_TeamTickets_C>(0x03F0, true);          // 0x03F0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_TerritoryControl_Bar_C>         _offW_TerritoryControl_TugofWar                                = new ExternalOffset<UW_TerritoryControl_Bar_C>(0x03F8, true); // 0x03F8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_VoipOwningPlayer_C>             _offW_VoipOwningPlayer                                         = new ExternalOffset<UW_VoipOwningPlayer_C>(0x0400, true);     // 0x0400(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UWidgetSwitcher>                   _offWidgetSwitcherTitle                                        = new ExternalOffset<UWidgetSwitcher>(0x0408, true);           // 0x0408(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<TEnumAsByte<EDeploymentProgressionState>> _offDeploy_State                                               = new ExternalOffset<TEnumAsByte<EDeploymentProgressionState>>(0x0410, false); // 0x0410(0x0001) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	private ExternalOffset<byte/*(bool)*/>                    _offFirst_Team_Selection                                       = new ExternalOffset<byte/*(bool)*/>(0x0411);                  // 0x0411(0x0001) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	private ExternalOffset<ASQPlayerController>               _offMy_PC                                                      = new ExternalOffset<ASQPlayerController>(0x0418, true);       // 0x0418(0x0008) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	private ExternalOffset<ASQPlayerState>                    _offMy_PS                                                      = new ExternalOffset<ASQPlayerState>(0x0420, true);            // 0x0420(0x0008) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	private ExternalOffset<UMaterialInstanceDynamic>          _offMI_BGFlag                                                  = new ExternalOffset<UMaterialInstanceDynamic>(0x0428, true);  // 0x0428(0x0008) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	private ExternalOffset<FTimerHandle>                      _offRespawn_Timer                                              = new ExternalOffset<FTimerHandle>(0x0430, false);             // 0x0430(0x0008) (Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash)
	private ExternalOffset<TEnumAsByte<EDeploymentScreen>>    _offDeploy_Screen                                              = new ExternalOffset<TEnumAsByte<EDeploymentScreen>>(0x0438, false); // 0x0438(0x0001) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	private ExternalOffset<byte/*(bool)*/>                    _offSpawn_Point_Sieged                                         = new ExternalOffset<byte/*(bool)*/>(0x0439);                  // 0x0439(0x0001) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	private ExternalOffset<FTimerHandle>                      _offUpdate_Timer                                               = new ExternalOffset<FTimerHandle>(0x0440, false);             // 0x0440(0x0008) (Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	private ExternalOffset<UW_DeploymentTutorial_C>           _offDeployment_Tutorial                                        = new ExternalOffset<UW_DeploymentTutorial_C>(0x0448, true);   // 0x0448(0x0008) (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	#endregion

	#region Props
	public FPointerToUberGraphFrame                           UberGraphFrame                                                 => _offUberGraphFrame.GetValue();
	public UWidgetAnimation                                   LoadFade                                                       => _offLoadFade.GetValue();
	public UWidgetAnimation                                   CentreTransition                                               => _offCentreTransition.GetValue();
	public UWidgetAnimation                                   BlackTransition                                                => _offBlackTransition.GetValue();
	public UWidgetAnimation                                   DeploymentOpenCloseAnim                                        => _offDeploymentOpenCloseAnim.GetValue();
	public UBorder                                            Blackout                                                       => _offBlackout.GetValue();
	public UImage                                             BlockInput                                                     => _offBlockInput.GetValue();
	public UMainMenu_Button_C                                 BottomBarRole                                                  => _offBottomBarRole.GetValue();
	public UWidgetSwitcher                                    BottomSwitcher                                                 => _offBottomSwitcher.GetValue();
	public UChallengeWindow_C                                 ChallengeGiveUp                                                => _offChallengeGiveUp.GetValue();
	public UChallengeWindow_C                                 ChallengeLeaveSquad                                            => _offChallengeLeaveSquad.GetValue();
	public UChallengeWindow_C                                 ChallengeLeaveTeam                                             => _offChallengeLeaveTeam.GetValue();
	public UImage                                             DeployArrow                                                    => _offDeployArrow.GetValue();
	public UMainMenu_Button_C                                 DeployButton                                                   => _offDeployButton.GetValue();
	public USizeBox                                           GiveupPanel                                                    => _offGiveupPanel.GetValue();
	public UImage                                             Image_1                                                        => _offImage_1.GetValue();
	public UImage                                             Image_9                                                        => _offImage_9.GetValue();
	public UImage                                             Image_BGFlag                                                   => _offImage_BGFlag.GetValue();
	public UImage                                             Image_FlagTopRight                                             => _offImage_FlagTopRight.GetValue();
	public UImage                                             Line                                                           => _offLine.GetValue();
	public UImage                                             LineBottom                                                     => _offLineBottom.GetValue();
	public UCanvasPanel                                       MainPanel                                                      => _offMainPanel.GetValue();
	public UMainMenu_Button_C                                 NAV_ROLES                                                      => _offNAV_ROLES.GetValue();
	public UMainMenu_Button_C                                 NAV_SQUADS                                                     => _offNAV_SQUADS.GetValue();
	public UMainMenu_Button_C                                 NAV_TEAMSELECT                                                 => _offNAV_TEAMSELECT.GetValue();
	public UOverlay                                           Overlay_DeployButton                                           => _offOverlay_DeployButton.GetValue();
	public UW_RoleSelect_C                                    RoleScreen                                                     => _offRoleScreen.GetValue();
	public USizeBox                                           Size_Centre                                                    => _offSize_Centre.GetValue();
	public UW_SquadSelect_C                                   SquadScreen                                                    => _offSquadScreen.GetValue();
	public UWidgetSwitcher                                    SwitchCentre                                                   => _offSwitchCentre.GetValue();
	public UWidgetSwitcher                                    SwitchLoad                                                     => _offSwitchLoad.GetValue();
	public UTextBlock                                         TB_ServerName                                                  => _offTB_ServerName.GetValue();
	public UTextBlock                                         TB_TeamName                                                    => _offTB_TeamName.GetValue();
	public UTextBlock                                         TB_Title                                                       => _offTB_Title.GetValue();
	public UW_TeamSelect_C                                    TeamScreen                                                     => _offTeamScreen.GetValue();
	public UHorizontalBox                                     TopNavigation                                                  => _offTopNavigation.GetValue();
	public UW_GameTime_C                                      W_GameTime                                                     => _offW_GameTime.GetValue();
	public UW_GameTime_C                                      W_GameTime_3                                                   => _offW_GameTime_3.GetValue();
	public UW_GiveUp_C                                        W_GiveUp                                                       => _offW_GiveUp.GetValue();
	public UW_PlayerRankAndRole_C                             W_PlayerRankAndRole                                            => _offW_PlayerRankAndRole.GetValue();
	public UW_TeamTickets_C                                   W_TeamTickets                                                  => _offW_TeamTickets.GetValue();
	public UW_TerritoryControl_Bar_C                          W_TerritoryControl_TugofWar                                    => _offW_TerritoryControl_TugofWar.GetValue();
	public UW_VoipOwningPlayer_C                              W_VoipOwningPlayer                                             => _offW_VoipOwningPlayer.GetValue();
	public UWidgetSwitcher                                    WidgetSwitcherTitle                                            => _offWidgetSwitcherTitle.GetValue();
	public TEnumAsByte<EDeploymentProgressionState>           Deploy_State                                                   => _offDeploy_State.GetValue();
	public byte/*(bool)*/                                     First_Team_Selection                                           => _offFirst_Team_Selection.GetValue();
	public ASQPlayerController                                My_PC                                                          => _offMy_PC.GetValue();
	public ASQPlayerState                                     My_PS                                                          => _offMy_PS.GetValue();
	public UMaterialInstanceDynamic                           MI_BGFlag                                                      => _offMI_BGFlag.GetValue();
	public FTimerHandle                                       Respawn_Timer                                                  => _offRespawn_Timer.GetValue();
	public TEnumAsByte<EDeploymentScreen>                     Deploy_Screen                                                  => _offDeploy_Screen.GetValue();
	public byte/*(bool)*/                                     Spawn_Point_Sieged                                             => _offSpawn_Point_Sieged.GetValue();
	public FTimerHandle                                       Update_Timer                                                   => _offUpdate_Timer.GetValue();
	public UW_DeploymentTutorial_C                            Deployment_Tutorial                                            => _offDeployment_Tutorial.GetValue();
	#endregion


}


}