// Name: Sq, Version: b21

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace UFT
{
//---------------------------------------------------------------------------
// Classes
//---------------------------------------------------------------------------

// WidgetBlueprintGeneratedClass W_Legend_MapIcons.W_Legend_MapIcons_C
// 0x0250 (0x0430 - 0x01E0)
public class UW_Legend_MapIcons_C : UUserWidget
{
	#region Offsets
	private ExternalOffset<UImage>                            _offImage_2                                                    = new ExternalOffset<UImage>(0x0230, true);                    // 0x0230(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offImage_14                                                   = new ExternalOffset<UImage>(0x0238, true);                    // 0x0238(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offImage_24                                                   = new ExternalOffset<UImage>(0x0240, true);                    // 0x0240(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offImage_25                                                   = new ExternalOffset<UImage>(0x0248, true);                    // 0x0248(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offImage_42                                                   = new ExternalOffset<UImage>(0x0250, true);                    // 0x0250(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offImage_52                                                   = new ExternalOffset<UImage>(0x0258, true);                    // 0x0258(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offImage_62                                                   = new ExternalOffset<UImage>(0x0260, true);                    // 0x0260(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offImage_63                                                   = new ExternalOffset<UImage>(0x0268, true);                    // 0x0268(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offImage_68                                                   = new ExternalOffset<UImage>(0x0270, true);                    // 0x0270(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offImage_79                                                   = new ExternalOffset<UImage>(0x0278, true);                    // 0x0278(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offImage_80                                                   = new ExternalOffset<UImage>(0x0280, true);                    // 0x0280(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offImage_85                                                   = new ExternalOffset<UImage>(0x0288, true);                    // 0x0288(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UImage>                            _offImage_105                                                  = new ExternalOffset<UImage>(0x0290, true);                    // 0x0290(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem                                               = new ExternalOffset<UW_LegendItem_C>(0x0298, true);           // 0x0298(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_1                                           = new ExternalOffset<UW_LegendItem_C>(0x02A0, true);           // 0x02A0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_2                                           = new ExternalOffset<UW_LegendItem_C>(0x02A8, true);           // 0x02A8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_3                                           = new ExternalOffset<UW_LegendItem_C>(0x02B0, true);           // 0x02B0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_4                                           = new ExternalOffset<UW_LegendItem_C>(0x02B8, true);           // 0x02B8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_5                                           = new ExternalOffset<UW_LegendItem_C>(0x02C0, true);           // 0x02C0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_6                                           = new ExternalOffset<UW_LegendItem_C>(0x02C8, true);           // 0x02C8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_7                                           = new ExternalOffset<UW_LegendItem_C>(0x02D0, true);           // 0x02D0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_8                                           = new ExternalOffset<UW_LegendItem_C>(0x02D8, true);           // 0x02D8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_9                                           = new ExternalOffset<UW_LegendItem_C>(0x02E0, true);           // 0x02E0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_10                                          = new ExternalOffset<UW_LegendItem_C>(0x02E8, true);           // 0x02E8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_11                                          = new ExternalOffset<UW_LegendItem_C>(0x02F0, true);           // 0x02F0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_12                                          = new ExternalOffset<UW_LegendItem_C>(0x02F8, true);           // 0x02F8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_13                                          = new ExternalOffset<UW_LegendItem_C>(0x0300, true);           // 0x0300(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_14                                          = new ExternalOffset<UW_LegendItem_C>(0x0308, true);           // 0x0308(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_15                                          = new ExternalOffset<UW_LegendItem_C>(0x0310, true);           // 0x0310(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_16                                          = new ExternalOffset<UW_LegendItem_C>(0x0318, true);           // 0x0318(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_17                                          = new ExternalOffset<UW_LegendItem_C>(0x0320, true);           // 0x0320(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_18                                          = new ExternalOffset<UW_LegendItem_C>(0x0328, true);           // 0x0328(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_19                                          = new ExternalOffset<UW_LegendItem_C>(0x0330, true);           // 0x0330(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_20                                          = new ExternalOffset<UW_LegendItem_C>(0x0338, true);           // 0x0338(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_21                                          = new ExternalOffset<UW_LegendItem_C>(0x0340, true);           // 0x0340(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_22                                          = new ExternalOffset<UW_LegendItem_C>(0x0348, true);           // 0x0348(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_25                                          = new ExternalOffset<UW_LegendItem_C>(0x0350, true);           // 0x0350(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_37                                          = new ExternalOffset<UW_LegendItem_C>(0x0358, true);           // 0x0358(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_38                                          = new ExternalOffset<UW_LegendItem_C>(0x0360, true);           // 0x0360(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_39                                          = new ExternalOffset<UW_LegendItem_C>(0x0368, true);           // 0x0368(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_40                                          = new ExternalOffset<UW_LegendItem_C>(0x0370, true);           // 0x0370(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_41                                          = new ExternalOffset<UW_LegendItem_C>(0x0378, true);           // 0x0378(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_42                                          = new ExternalOffset<UW_LegendItem_C>(0x0380, true);           // 0x0380(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_43                                          = new ExternalOffset<UW_LegendItem_C>(0x0388, true);           // 0x0388(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_44                                          = new ExternalOffset<UW_LegendItem_C>(0x0390, true);           // 0x0390(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_45                                          = new ExternalOffset<UW_LegendItem_C>(0x0398, true);           // 0x0398(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_46                                          = new ExternalOffset<UW_LegendItem_C>(0x03A0, true);           // 0x03A0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_49                                          = new ExternalOffset<UW_LegendItem_C>(0x03A8, true);           // 0x03A8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_58                                          = new ExternalOffset<UW_LegendItem_C>(0x03B0, true);           // 0x03B0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_59                                          = new ExternalOffset<UW_LegendItem_C>(0x03B8, true);           // 0x03B8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_60                                          = new ExternalOffset<UW_LegendItem_C>(0x03C0, true);           // 0x03C0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_61                                          = new ExternalOffset<UW_LegendItem_C>(0x03C8, true);           // 0x03C8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_62                                          = new ExternalOffset<UW_LegendItem_C>(0x03D0, true);           // 0x03D0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_63                                          = new ExternalOffset<UW_LegendItem_C>(0x03D8, true);           // 0x03D8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_64                                          = new ExternalOffset<UW_LegendItem_C>(0x03E0, true);           // 0x03E0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_65                                          = new ExternalOffset<UW_LegendItem_C>(0x03E8, true);           // 0x03E8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_66                                          = new ExternalOffset<UW_LegendItem_C>(0x03F0, true);           // 0x03F0(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_70                                          = new ExternalOffset<UW_LegendItem_C>(0x03F8, true);           // 0x03F8(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_71                                          = new ExternalOffset<UW_LegendItem_C>(0x0400, true);           // 0x0400(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_72                                          = new ExternalOffset<UW_LegendItem_C>(0x0408, true);           // 0x0408(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_76                                          = new ExternalOffset<UW_LegendItem_C>(0x0410, true);           // 0x0410(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_79                                          = new ExternalOffset<UW_LegendItem_C>(0x0418, true);           // 0x0418(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_85                                          = new ExternalOffset<UW_LegendItem_C>(0x0420, true);           // 0x0420(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	private ExternalOffset<UW_LegendItem_C>                   _offW_LegendItem_C_87                                          = new ExternalOffset<UW_LegendItem_C>(0x0428, true);           // 0x0428(0x0008) (BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	#endregion

	#region Props
	public UImage                                             Image_2                                                        => _offImage_2.GetValue();
	public UImage                                             Image_14                                                       => _offImage_14.GetValue();
	public UImage                                             Image_24                                                       => _offImage_24.GetValue();
	public UImage                                             Image_25                                                       => _offImage_25.GetValue();
	public UImage                                             Image_42                                                       => _offImage_42.GetValue();
	public UImage                                             Image_52                                                       => _offImage_52.GetValue();
	public UImage                                             Image_62                                                       => _offImage_62.GetValue();
	public UImage                                             Image_63                                                       => _offImage_63.GetValue();
	public UImage                                             Image_68                                                       => _offImage_68.GetValue();
	public UImage                                             Image_79                                                       => _offImage_79.GetValue();
	public UImage                                             Image_80                                                       => _offImage_80.GetValue();
	public UImage                                             Image_85                                                       => _offImage_85.GetValue();
	public UImage                                             Image_105                                                      => _offImage_105.GetValue();
	public UW_LegendItem_C                                    W_LegendItem                                                   => _offW_LegendItem.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_1                                               => _offW_LegendItem_C_1.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_2                                               => _offW_LegendItem_C_2.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_3                                               => _offW_LegendItem_C_3.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_4                                               => _offW_LegendItem_C_4.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_5                                               => _offW_LegendItem_C_5.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_6                                               => _offW_LegendItem_C_6.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_7                                               => _offW_LegendItem_C_7.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_8                                               => _offW_LegendItem_C_8.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_9                                               => _offW_LegendItem_C_9.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_10                                              => _offW_LegendItem_C_10.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_11                                              => _offW_LegendItem_C_11.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_12                                              => _offW_LegendItem_C_12.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_13                                              => _offW_LegendItem_C_13.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_14                                              => _offW_LegendItem_C_14.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_15                                              => _offW_LegendItem_C_15.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_16                                              => _offW_LegendItem_C_16.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_17                                              => _offW_LegendItem_C_17.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_18                                              => _offW_LegendItem_C_18.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_19                                              => _offW_LegendItem_C_19.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_20                                              => _offW_LegendItem_C_20.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_21                                              => _offW_LegendItem_C_21.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_22                                              => _offW_LegendItem_C_22.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_25                                              => _offW_LegendItem_C_25.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_37                                              => _offW_LegendItem_C_37.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_38                                              => _offW_LegendItem_C_38.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_39                                              => _offW_LegendItem_C_39.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_40                                              => _offW_LegendItem_C_40.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_41                                              => _offW_LegendItem_C_41.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_42                                              => _offW_LegendItem_C_42.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_43                                              => _offW_LegendItem_C_43.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_44                                              => _offW_LegendItem_C_44.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_45                                              => _offW_LegendItem_C_45.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_46                                              => _offW_LegendItem_C_46.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_49                                              => _offW_LegendItem_C_49.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_58                                              => _offW_LegendItem_C_58.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_59                                              => _offW_LegendItem_C_59.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_60                                              => _offW_LegendItem_C_60.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_61                                              => _offW_LegendItem_C_61.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_62                                              => _offW_LegendItem_C_62.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_63                                              => _offW_LegendItem_C_63.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_64                                              => _offW_LegendItem_C_64.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_65                                              => _offW_LegendItem_C_65.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_66                                              => _offW_LegendItem_C_66.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_70                                              => _offW_LegendItem_C_70.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_71                                              => _offW_LegendItem_C_71.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_72                                              => _offW_LegendItem_C_72.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_76                                              => _offW_LegendItem_C_76.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_79                                              => _offW_LegendItem_C_79.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_85                                              => _offW_LegendItem_C_85.GetValue();
	public UW_LegendItem_C                                    W_LegendItem_C_87                                              => _offW_LegendItem_C_87.GetValue();
	#endregion


}


}